#!/usr/bin/env python
# coding=utf-8

# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from __future__ import annotations

import json
from dataclasses import dataclass, field
from enum import IntEnum
from typing import TYPE_CHECKING, Any

from rich import box
from rich.console import Console, Group
from rich.panel import Panel
from rich.rule import Rule
from rich.syntax import Syntax
from rich.table import Table
from rich.text import Text
from rich.tree import Tree

from smolagents.utils import sanitize_for_rich

if TYPE_CHECKING:
    from smolagents.memory import MemoryStep


__all__ = ["AgentLogger", "LogLevel", "Monitor", "TokenUsage", "Timing"]


@dataclass
class TokenUsage:
    """
    Contains the token usage information for a given step or run.

    Attributes:
        input_tokens: Number of tokens in the prompt sent to the model.
        output_tokens: Number of tokens generated by the model.
        total_tokens: Sum of input and output tokens (computed automatically).
    """

    input_tokens: int
    output_tokens: int
    total_tokens: int = field(init=False)

    def __post_init__(self) -> None:
        self.total_tokens = self.input_tokens + self.output_tokens

    def dict(self) -> dict[str, int]:
        """Return a plain dictionary representation of the token usage."""
        return {
            "input_tokens": self.input_tokens,
            "output_tokens": self.output_tokens,
            "total_tokens": self.total_tokens,
        }


@dataclass
class Timing:
    """
    Contains the timing information for a given step or run.

    Attributes:
        start_time: Unix timestamp (seconds) when the step started.
        end_time: Unix timestamp (seconds) when the step finished, or ``None``
            if the step has not yet completed.
    """

    start_time: float
    end_time: float | None = None

    @property
    def duration(self) -> float | None:
        """Elapsed time in seconds, or ``None`` if the step has not finished."""
        return None if self.end_time is None else self.end_time - self.start_time

    def dict(self) -> dict[str, float | None]:
        """Return a plain dictionary representation of the timing information."""
        return {
            "start_time": self.start_time,
            "end_time": self.end_time,
            "duration": self.duration,
        }

    def __repr__(self) -> str:
        return f"Timing(start_time={self.start_time}, end_time={self.end_time}, duration={self.duration})"


class Monitor:
    """Tracks token usage and step durations across an agent run.

    Args:
        tracked_model: The model instance being monitored.
        logger: An :class:`AgentLogger` used to emit per-step summaries.
    """

    def __init__(self, tracked_model: Any, logger: AgentLogger) -> None:
        self.step_durations: list[float | None] = []
        self.tracked_model = tracked_model
        self.logger = logger
        self.total_input_token_count: int = 0
        self.total_output_token_count: int = 0

    def get_total_token_counts(self) -> TokenUsage:
        """Return the cumulative token usage across all steps recorded so far."""
        return TokenUsage(
            input_tokens=self.total_input_token_count,
            output_tokens=self.total_output_token_count,
        )

    def reset(self) -> None:
        """Reset all accumulated metrics to zero."""
        self.step_durations = []
        self.total_input_token_count = 0
        self.total_output_token_count = 0

    def update_metrics(self, step_log: MemoryStep) -> None:
        """Update the metrics of the monitor.

        Appends the step duration to :attr:`step_durations` and accumulates
        token counts from *step_log*.  A brief summary is printed to the
        console at ``LogLevel.INFO``.

        Args:
            step_log: The completed memory step whose metrics should be
                recorded.
        """
        step_duration = step_log.timing.duration
        self.step_durations.append(step_duration)
        console_outputs = f"[Step {len(self.step_durations)}: Duration {step_duration:.2f} seconds"

        if step_log.token_usage is not None:
            self.total_input_token_count += step_log.token_usage.input_tokens
            self.total_output_token_count += step_log.token_usage.output_tokens
            console_outputs += (
                f"| Input tokens: {self.total_input_token_count:,} | Output tokens: {self.total_output_token_count:,}"
            )
        console_outputs += "]"
        self.logger.log(Text(console_outputs, style="dim"), level=1)


class LogLevel(IntEnum):
    """Verbosity levels for :class:`AgentLogger`.

    Attributes:
        OFF: Suppress all output.
        ERROR: Print only error messages.
        INFO: Normal output (default).
        DEBUG: Detailed output including raw messages sent to the model.
    """

    OFF = -1
    ERROR = 0
    INFO = 1
    DEBUG = 2


YELLOW_HEX = "#d4b702"


class AgentLogger:
    """Console logger for smolagents with Rich-based formatting.

    Args:
        level: Minimum verbosity level to emit.  Messages below this level
            are silently discarded.  Defaults to :attr:`LogLevel.INFO`.
        console: An optional pre-configured Rich :class:`~rich.console.Console`
            instance.  A default console is created when *None* is passed.
    """

    def __init__(self, level: LogLevel = LogLevel.INFO, console: Console | None = None) -> None:
        self.level = level
        if console is None:
            self.console = Console(highlight=False)
        else:
            self.console = console

    def log(self, *args: Any, level: int | str | LogLevel = LogLevel.INFO, **kwargs: Any) -> None:
        """Log a message to the console.

        The message is only printed when *level* is less than or equal to
        :attr:`self.level`.

        Args:
            *args: Positional arguments forwarded to
                :meth:`rich.console.Console.print`.
            level: Minimum verbosity threshold for this message.  May be an
                :class:`int`, a case-insensitive :class:`str` name (e.g.
                ``"debug"``), or a :class:`LogLevel` enum member.  Defaults to
                :attr:`LogLevel.INFO`.
            **kwargs: Keyword arguments forwarded to
                :meth:`rich.console.Console.print`.
        """
        if isinstance(level, str):
            level = LogLevel[level.upper()]
        if level <= self.level:
            self.console.print(*args, **kwargs)

    def log_error(self, error_message: str) -> None:
        """Log an error message in bold red at :attr:`LogLevel.ERROR`.

        Args:
            error_message: The error text to display.
        """
        self.log(Text(sanitize_for_rich(error_message), style="bold red"), level=LogLevel.ERROR)

    def log_markdown(self, content: str, title: str | None = None, level: LogLevel = LogLevel.INFO, style: str = YELLOW_HEX) -> None:
        """Render *content* as syntax-highlighted Markdown.

        Args:
            content: Raw Markdown text to display.
            title: Optional heading shown above the content as a horizontal
                rule.  When ``None`` the rule is omitted.
            level: Verbosity level for this message.  Defaults to
                :attr:`LogLevel.INFO`.
            style: Rich color string applied to the title rule.  Defaults to
                the smolagents yellow accent color.
        """
        markdown_content = Syntax(
            content,
            lexer="markdown",
            theme="github-dark",
            word_wrap=True,
        )
        if title:
            self.log(
                Group(
                    Rule(
                        "[bold italic]" + title,
                        align="left",
                        style=style,
                    ),
                    markdown_content,
                ),
                level=level,
            )
        else:
            self.log(markdown_content, level=level)

    def log_code(self, title: str, content: str, level: int = LogLevel.INFO) -> None:
        """Render *content* as a syntax-highlighted Python code block.

        Args:
            title: Panel heading shown above the code block.
            content: Python source code to display.
            level: Verbosity level for this message.  Defaults to
                :attr:`LogLevel.INFO`.
        """
        self.log(
            Panel(
                Syntax(
                    content,
                    lexer="python",
                    theme="monokai",
                    word_wrap=True,
                ),
                title="[bold]" + title,
                title_align="left",
                box=box.HORIZONTALS,
            ),
            level=level,
        )

    def log_rule(self, title: str, level: int = LogLevel.INFO) -> None:
        """Print a horizontal rule with *title* as a section divider.

        Args:
            title: Text displayed in the center of the rule.
            level: Verbosity level for this message.  Defaults to
                :attr:`LogLevel.INFO`.
        """
        self.log(
            Rule(
                "[bold white]" + title,
                characters="━",
                style=YELLOW_HEX,
            ),
            level=LogLevel.INFO,
        )

    def log_task(self, content: str, subtitle: str, title: str | None = None, level: LogLevel = LogLevel.INFO) -> None:
        """Display a new-task panel with *content* as the task description.

        The *content* and *subtitle* are rendered as plain :class:`~rich.text.Text`
        to avoid Rich markup-parser crashes caused by arbitrary tool payloads
        that may contain stray ``[/...]`` sequences.

        Args:
            content: The task prompt or description.
            subtitle: Short label shown at the bottom-left of the panel (e.g.
                the model identifier).
            title: Optional string appended to the default ``"New run"`` panel
                heading.
            level: Verbosity level for this message.  Defaults to
                :attr:`LogLevel.INFO`.
        """
        safe_content = sanitize_for_rich(content)
        safe_subtitle = sanitize_for_rich(subtitle)
        content_text = Text("\n") + Text(safe_content, style="bold") + Text("\n")
        subtitle_text = Text(safe_subtitle)
        self.log(
            Panel(
                content_text,
                title="[bold]New run" + (f" - {title}" if title else ""),
                subtitle=subtitle_text,
                border_style=YELLOW_HEX,
                subtitle_align="left",
            ),
            level=level,
        )

    def log_messages(self, messages: list[dict[str, Any]], level: LogLevel = LogLevel.DEBUG) -> None:
        """Dump a list of chat *messages* as formatted JSON.

        Intended for debugging: logs the raw message dicts sent to the model.

        Args:
            messages: List of message objects (each must expose a ``.dict()``
                method) to serialize and display.
            level: Verbosity level for this message.  Defaults to
                :attr:`LogLevel.DEBUG`.
        """
        messages_as_string = "\n".join([json.dumps(message.dict(), indent=4) for message in messages])
        self.log(
            Syntax(
                messages_as_string,
                lexer="markdown",
                theme="github-dark",
                word_wrap=True,
            ),
            level=level,
        )

    def visualize_agent_tree(self, agent: Any) -> None:
        """Print a Rich tree representation of *agent* and its managed sub-agents.

        Each node in the tree shows the agent class, model ID, available tools,
        and — for :class:`~smolagents.CodeAgent` instances — the list of
        authorized imports.

        Args:
            agent: The root agent whose hierarchy should be visualized.
        """

        def create_tools_section(tools_dict: dict[str, Any]) -> Group:
            table = Table(show_header=True, header_style="bold")
            table.add_column("Name", style="#1E90FF")
            table.add_column("Description")
            table.add_column("Arguments")

            for name, tool in tools_dict.items():
                args = [
                    f"{arg_name} (`{info.get('type', 'Any')}`{', optional' if info.get('optional') else ''}): {info.get('description', '')}"
                    for arg_name, info in getattr(tool, "inputs", {}).items()
                ]
                table.add_row(name, getattr(tool, "description", str(tool)), "\n".join(args))

            return Group("\U0001f6e0️ [italic #1E90FF]Tools:[/italic #1E90FF]", table)

        def get_agent_headline(agent: Any, name: str | None = None) -> str:
            name_headline = f"{name} | " if name else ""
            return f"[bold {YELLOW_HEX}]{name_headline}{agent.__class__.__name__} | {agent.model.model_id}"

        def build_agent_tree(parent_tree: Tree, agent_obj: Any) -> None:
            """Recursively build the Rich tree for *agent_obj* under *parent_tree*."""
            parent_tree.add(create_tools_section(agent_obj.tools))

            if agent_obj.managed_agents:
                agents_branch = parent_tree.add("\U0001f916 [italic #1E90FF]Managed agents:")
                for name, managed_agent in agent_obj.managed_agents.items():
                    agent_tree = agents_branch.add(get_agent_headline(managed_agent, name))
                    if managed_agent.__class__.__name__ == "CodeAgent":
                        agent_tree.add(
                            f"✅ [italic #1E90FF]Authorized imports:[/italic #1E90FF] {managed_agent.additional_authorized_imports}"
                        )
                    agent_tree.add(f"\U0001f4dd [italic #1E90FF]Description:[/italic #1E90FF] {managed_agent.description}")
                    build_agent_tree(agent_tree, managed_agent)

        main_tree = Tree(get_agent_headline(agent))
        if agent.__class__.__name__ == "CodeAgent":
            main_tree.add(
                f"✅ [italic #1E90FF]Authorized imports:[/italic #1E90FF] {agent.additional_authorized_imports}"
            )
        build_agent_tree(main_tree, agent)
        self.console.print(main_tree)
